version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest    
    container_name: mosquitto
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - mqtt
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USER_DIR}/data/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ${USER_DIR}/data/mosquitto/log:/mosquitto/log
      - mqtt_data:/mosquitto/data
          

networks:
  mqtt:
    external: true

volumes:
  mqtt_data: